<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="PC" name="TestNG.TestNG_Keywords" tests="16" failures="0" timestamp="1 Dec 2020 07:16:04 GMT" time="12.078" errors="1">
  <testcase name="TC" time="0.143" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.073" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.004" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.015" classname="TestNG.TestNG_Keywords"/>
  <testcase name="VerifyPin" time="0.000" classname="TestNG.TestNG_Keywords">
    <skipped/>
  </testcase> <!-- VerifyPin -->
  <testcase name="TC" time="0.004" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.010" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC1" time="0.061" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.016" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC5" time="6.183" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.210" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.075" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC" time="0.031" classname="TestNG.TestNG_Keywords"/>
  <testcase name="TC2" time="0.022" classname="TestNG.TestNG_Keywords"/>
  <testcase name="loginToApp" time="5.227" classname="TestNG.TestNG_Keywords">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNG.TestNG_Keywords.loginToApp() didn&#039;t finish within the time-out 5000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG.TestNG_Keywords.loginToApp() didn't finish within the time-out 5000
]]>
    </error>
  </testcase> <!-- loginToApp -->
  <testcase name="TC4" time="0.004" classname="TestNG.TestNG_Keywords"/>
</testsuite> <!-- TestNG.TestNG_Keywords -->
